
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
namespace KerKonConConExt
{
	static class Version
	{
		public const int major = 1;
		public const int minor = 25;
		public const int patch = 0;
		public const int build = 2;
		public const string Number = "1.25.0.2";
		public const string Text = Number + " Unofficial";
	}
}
